language: ruby
rvm:
- 2.2
before_script:
- gpg --passphrase "$KEY" --decrypt --no-use-agent --output config/application.yml config/application.yml.asc
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec cucumber
after_script:
- bundle exec rake send_to_codeclimate
addons:
  code_climate:
    repo_token: a823be3184ca968a58b1834ec87fe2335366346fe839e2d38d38d97b4a870ea4
env:
  - secure: "WqBTwwaITf4214Xvejf7KSAzo+4+2WQgBYMENhhtVQuXZQ+UPk5nPNEuT59vGiWpcdP+Xvk+XzYvRUVRMTBJw69dVeirii5vrPXNl5iC7qbnNtbIxWbczmkEdZofaZSGEZscbs136MX1UaPKlo3tdwIjYyAccuY1hrGDrn8aGubHKOScC+eGEirEqqYNPQsTX0NH+/xtaHlon0zLP/bvnedIn2a0XoN07WC7Qolfrcb9ugX9b+0FsJl50ImlyGp3d3p6UDyXr+g9wAreeRSDlnnmTV3f1vwWR0H3AEj171YP+eXfGFiqV7dELKRt8SWSYwZzmInMWBwFIULu3o/rpPfODP6lmYAnyXm+qZCOWymEzvvKxSQnSbCUFj30DTJ+LbgnPyd2xNl+IzBJYkkFzPwvOYoePAwiiQvv/3eLMDU1eEdyydW5+8kS7dUZOBwwl9kh8SfVAs3tGTugCnQBn4O3R1T1AJlHfNXY8B5Wiy3PC779ZuganrxfbDhK7pLPoSeBkhZP06Ffhs7MfgigZUR3h4K+t1mRFkEWuCEYh5OwkHGpuFSoxAWVjfRI+RMrlaPB4LJfHCeMvJw/3mXm11JGxQJLLdLFuhe8ruSpoRHtO/0PYg1Q6Qa8BFHJDZ0E8F4thnPFDb1fPnUVIgfKmkE8mnLaQoO7JTHuvyhvyDA="
